<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
?>
<?php if($this->getCollection()->getSize()): ?>
<div class="toolbar clearfix">
  <div class="user-controls">
    <?php if( $this->isExpanded() ): ?>
      <?php if( $this->isEnabledViewSwitcher() ): ?>
        <div class="view-mode">
          <?php $_modes = $this->getModes(); ?>
          <?php if($_modes && count($_modes)>1): ?>
          <label><?php echo $this->__('View as') ?>:</label>
          <p class="modes">
          <?php foreach ($this->getModes() as $_code=>$_label): ?>
            <?php $_class = strtolower($_code); ?>
            <?php $_icon = $_class == 'grid' ? 'icon-th' : 'icon-list'; ?>
            <?php if($this->isModeActive($_code)): ?>
              <strong title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></strong>&nbsp;
            <?php else: ?>
              <a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></a>&nbsp;
            <?php endif; ?>
          <?php endforeach; ?>
          </p>
          <?php endif; ?>
        </div>
        <?php endif; ?>

        <div class="sort-by">
          <label><?php echo $this->__('Sort By') ?></label>
          <select class="input-small" onchange="setLocation(this.value)">
          <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
            <option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
              <?php echo $this->__($_order) ?>
            </option>
          <?php endforeach; ?>
          </select>
          <?php if($this->getCurrentDirection() == 'desc'): ?>
            <a href="<?php echo $this->getOrderUrl(null, 'asc') ?>" title="<?php echo $this->__('Set Ascending Direction') ?>"><img src="<?php echo $this->getSkinUrl('images/i_desc_arrow.gif') ?>" alt="<?php echo $this->__('Set Ascending Direction') ?>" class="v-middle" /></a>
           <?php else: ?>
             <a href="<?php echo $this->getOrderUrl(null, 'desc') ?>" title="<?php echo $this->__('Set Descending Direction') ?>"><img src="<?php echo $this->getSkinUrl('images/i_asc_arrow.gif') ?>" alt="<?php echo $this->__('Set Descending Direction') ?>" class="v-middle" /></a>
          <?php endif; ?>
        </div>
    <?php endif; ?>

    <div class="page-size">
      <label><?php echo $this->__('Page Size') ?></label>
      <select class="input-mini" onchange="setLocation(this.value)">
        <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
        <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
          <?php echo $_limit ?>
        </option>
        <?php endforeach; ?>
      </select>
    </div>

  </div>

  <?php echo $this->getPagerHtml() ?>

</div>
<?php endif ?>
