<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
  <head>
    <?php echo $this->getChildHtml('head') ?>
    </head>
  <body>
    <?php echo $this->getChildHtml('after_body_start') ?>

    <div id="page-root">
      <?php echo $this->getChildHtml('header') ?>
      <div class="container">
        <div class="content">
          <?php echo $this->getChildHtml('breadcrumbs') ?>
          <?php echo $this->getChildHtml('global_notices') ?>
          <?php echo $this->getChildHtml('global_messages') ?>
          <div class="row">
            <div class="span2">
              <?php echo $this->getChildHtml('left') ?>
            </div>
            <div class="span10">
              <?php echo $this->getChildHtml('content') ?>
            </div>
          </div>
        </div>
      </div>
      <div id="page-root-footer"></div>
    </div>

    <footer id="page-footer">
      <div class="container">
        <?php echo $this->getChildHtml('footer') ?>
      </div>
    </footer>

    <?php echo $this->getChildHtml('before_body_end') ?>
    <?php echo $this->getAbsoluteFooter() ?>
  </body>
</html>