<div id="page-header">
<div class="container">
  <div class="row">
    <div class="header-content clearfix">
    <div class="span4 logo-container">
      <?php if ($this->getIsHomePage()):?>
        <h1 class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
      <?php else:?>
        <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
      <?php endif?>
    </div>
    <div class="quick-access span8">
      <?php echo $this->getChildHtml('topSearch') ?>
      <?php echo $this->getChildHtml('topLinks') ?>
      <?php /* echo $this->getChildHtml('store_language') */ ?>
    </div>
    <?php echo $this->getChildHtml('topContainer'); ?>
  </div>
  </div>
</div>
</div>
<?php echo $this->getChildHtml('topMenu') ?>
