
<div id="page-header">
  <div class="page-header-content container">
    <div class="header-content clearfix">
      <div class="logo-container pull-left">
        <?php if ($this->getIsHomePage()):?>
          <h1 class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
        <?php else:?>
          <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
        <?php endif?>
      </div>

      <div class="header-alternate pull-right">
        <?php echo $this->getChildHtml('topLinks') ?>
        <?php echo $this->getChildHtml('topContainer'); ?>
        <?php /* echo $this->getChildHtml('store_language') */ ?>
      </div>
    </div>

    <div class="navbar navbar-atp" id="site-navbar"><div class="navbar-inner">
      <?php echo $this->getChildHtml('topMenu') ?>
      <div class="navbar-alternate pull-right">
        <?php echo $this->getChildHtml('topSearch') ?>
        <?php echo $this->getChildHtml('topMenuAlternate') ?>
      </div>
    </div></div>
  </div>
</div>