<?php $_product = $this->getProduct(); ?>
<?php $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product); ?>

<ul class="add-to-links">
<?php if ($this->helper('wishlist')->isAllow()) : ?>
    <li><a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, this.href); return false;" class="link-wishlist"><i class="icon-heart"></i> <span><?php echo $this->__('Add to Wishlist') ?></span></a></li>
<?php endif; ?>
<?php
    $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product);
?>
<?php if($_compareUrl) : ?>
    <li><a href="<?php echo $_compareUrl ?>" class="link-compare"><i class="icon-bookmark"></i> <span><?php echo $this->__('Add to Compare') ?></a></span></li>
<?php endif; ?>
</ul>
