
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>
<p class="product-image product-image-zoom">
<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
<?php
  $_full = (string)$this->helper('catalog/image')->init($_product, 'image');
$_img = '<img id="image" src="'.$this->helper('catalog/image')->init($_product, 'image')->keepAspectRatio(true)->resize(390, 540).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
  echo '<a id="product-zoom" class="MagicTouch" href="' . $_full . '">' . $_helper->productAttribute($_product, $_img, 'image') . '</a>';
?>
<?php else: ?>
<?php
  $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->keepAspectRatio(true)->resize(280).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
  echo $_helper->productAttribute($_product, $_img, 'image');
?>
<?php endif; ?>
</p>
<?php $images = $this->getGalleryImages(); ?>
<?php $count = count($images); ?>
<?php if ($count): ?>
<div class="more-views side">
  <ul>
    <?php foreach ($images as $_image): ?>
    <li><?php $data  = ' href="' . $_image->getUrl() . '"'; ?>
        <?php $data .= ' rev="' . $this->helper('catalog/image')->init($_product, 'image', $_image->getFile())->keepAspectRatio(true)->resize(390, 540) . '"'; ?>
      <a rel="product-zoom" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>" <?php print $data; ?>><img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $_image->getFile())->resize(56, 77); ?>" width="56" height="77" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" /></a>
      </li>
    <?php endforeach; ?>
  </ul>
</div>
<?php endif; ?>
<?php $config = $this->getConfigGallery(); ?>
<?php if (count($config)): ?>
<?php foreach ($config as $_image): ?>
   <?php $product = $_image->getProduct(); ?>
  <meta name="configurable-image" data-product-id="<?php print $product->getId() ?>" data-title="<?php echo $this->htmlEscape($_image->getLabel()) ?>" data-zoom="<?php print $_image->getUrl() ?>" data-thumb="<?php print $this->helper('catalog/image')->init($_product, 'thumbnail', $_image->getFile())->resize(56, 77); ?>" data-src="<?php print $this->helper('catalog/image')->init($product, 'image', $_image->getFile())->keepAspectRatio(true)->resize(390, 540) ?>">
<?php endforeach ?>
<?php endif; ?>
