<form id="search_mini_form" action="<?php echo $this->helper('catalogsearch')->getResultUrl() ?>" method="get" class="navbar-form">
  <input class="input-medium search-query" id="search" type="text" placeholder="<?php echo $this->__('Search for keyword or item #') ?>" name="<?php echo $this->helper('catalogsearch')->getQueryParamName() ?>">
 <button class="btn" type="submit"><i class="icon-search"></i> <span><?php echo $this->__('Search') ?></span></button>
</form>