<?php
$_productCollection = $this->getProducts();
$_helper = $this->helper('catalog/output');

?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/facebooktab.css'); ?>" media="all"/>
<script type="text/javascript">
function goToUrl(url) {
  document.setLocation(url);
}
</script>
<div class="banner" style="display:none">
  <?php echo $this->getChildHtml('facebook.banner'); ?>
</div>
<div class="fb-list">
  <div class="category-products">
    <?php if (!$_productCollection->count()): ?>
      <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    <?php else: ?>
    <div class="category-products">
      <?php $_iterator = 0; ?>
      <ol class="products-list">
        <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if (++$_iterator == sizeof($_productCollection)): ?> last<?php endif; ?>">
          <div class="left_column">
            <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" target="_blank" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/></a>
          </div>
          <div class="right_column">
            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" target="_blank"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
            </h2>
             <?php // Product description ?>
            <?php echo $this->getPriceHtml($_product, true) ?>
            <div class="product-shop">
              <div class="f-fix">
                <?php if ($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
                <div class="desc std">
                  <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                </div>
                <ul class="add-to-links">
                  <li><span><a href="<?php echo $_product->getProductUrl() ?>" target="_blank" class="view_details"><?php echo $this->__("View details"); ?></a></span></li>
                </ul>
              </div>
            </div>
          </div>
        </li>
        <?php endforeach; ?>
      </ol>
    </div>
    <?php endif; ?>
  </div>
</div>
